package com.example.hangman2;

import java.util.Arrays;
import java.util.Collections;

public class questionDatabase {
	public static question[] questions=new question[]{
		new question("ողբերգ", "եղերերգ"),
		new question("տնանկ", "անօթևան"),
		new question("բարեկեցություն", "բարօրություն"),
		new question("հեղել", "ոթել"),
		new question("խղճալ", "ողոքել"),
		new question("բարձրաձայն", "որոտընդոստ"),
		new question("նահանջել", "ընկրկել"),
		new question("հյուրընկալ", "ասպնջական"),
		new question("դիվան", "ատյան"),
		new question("ակնախոռոչ", "ակնակապիճ"),
		new question("կռվարար", "ամբարիշտ"),
		new question("ցոփ", "արբշիռ"),
		new question("էգ ձի", "զամբիկ"),
		new question("մթում շոշափել", "խարխափել"),
		new question("սևամորթ", "խափշիկ"),
		new question("չարախոսանք", "բամբասանք"),
		new question("երես առնել", "հղփանալ"),
		new question("թմրել", "ընդարմանալ"),
		new question("մտրակ", "լախտ"),
		new question("ծավի", "լաջվարդ"),
		new question("տխեղծ", "խեղանդամ"),
		new question("լեփ", "լեցուն"),
		new question("հյուսն", "ատաղծագործ"),
		new question("անտերունչ", "բարձիթողի"),
		new question("ապառաժ", "որձաքար"),
		new question("այծի մազից գործված կոշտ կտոր", "այծենակաճ"),
		new question("նետաման", "կապարճ"),
		new question("պտուղ", "երախայրիք"),
		new question("շռայլություն", "զեխություն"),
		new question("ծաղրածու", "խեղկատակ"),
		new question("սպրդել", "ճողոպրել"),
		new question("աստանդական", "պանդուխտ"),
		new question("հագուստի փեշ", "քղանցք"),
		new question("հեղգ", "դատարկապորտ"),
		new question("մեծ մոմ", "կերոն"),
		new question("մեծախոս", "պոռոտախոս"),
		new question("կենգուրու", "ագեվազ"),
		new question("կյանքի վերջին րոպեները", "հոգեվարք"),
		new question("մեղադրել", "ամբաստանել"),
		new question("վավաշոտ", "պագշոտ"),
		new question("նողկանք", "պժգանք"),
		new question("տանջել", "լլկել"),
		new question("գծուծ", "կծծի"),
		new question("ձիու ձայնը", "վրնջյուն"),
		new question("կանաչ տերևների ձայն", "սոսափ"),
		new question("ջուրն ընկած առարկայի ձայն", "ճողփյուն"),
		new question("ճռվողյուն", "գեղգեղանք"),
		new question("օձերի խումբ", "նքողնակ"),
		new question("ձիերի խումբ", "երամակ"),
		new question("աղվեսների խումբ", "ճահուկ"),
		new question("այծերի խումբ", "հորան"),
		new question("մեղուների խումբ", "պարս"),
		new question("խոզերի խումբ", "բոլուկ"),
		new question("որսաշների խումբ", "ասպականի"),
		new question("արու գառ", "ամիկ"),
		new question("արու այծ", "նոխազ"),
		new question("էգ ուլ", "ալոջ"),
		new question("արու ձի", "հովատակ"),
		new question("արու թռչուն", "վարուժան"),
		new question("արու ուղտ", "մալախ"),
		new question("ուղտի ձագ", "կոզռակ"),
		new question("արու բազե", "ճուռակ"),
		new question("հավի էգ ձագ", "վառէկ"),
		new question("մեկ տարեկան էգ հորթ", "երինջ"),
		new question("կրոնական", "աբբահայր"),
		new question("յասաման", "եղրևանի"),
		new question("պտտահողմ", "թաթառ"),
		new question("հառնաշփոթ", "խառնիճաղանջ"),
		new question("ակադեմիա", "կաճառ"),
		new question("հավերժահարս", "պարիկ"),
		new question("մոխրագույն ձի", "մողոշիկ"),
		new question("թխակարմիր ձի", "շառատ"),
		new question("արագընթաց  ձի", "արաբիկ"),
		new question("սև պուտերով ձի", "ճայիկ"),
		new question("բոցագույն ձի", "աշխետ"),
		new question("նժույգ", "երիվար"),
		new question("հեծնելու ձի", "ռահվար"),
		new question("բեռներ կրող կենդանի", "գրաստ"),
		new question("վայրի բադ", "մրտիմ"),
		new question("ջահել եզ", "արջառ"),
		new question("կռունկների խումբ", "խորդերամ"),
		new question("մայր գոմեշ", "մատակ"),
		new question("կղզիների խումբ", "արշիպելագ"),
		new question("նավերի խումբ", "տորմիղ"),
		new question("օրինական ամուսին ունեցող կին", "արամբի"),
		new question("օրինական կին ունեցող տղամարդ", "կանամբի"),
		new question("չամուսնացած տղամարդ", "ամուրի"),
		new question("անասունների կեր", "ճարակ"),
		new question("կրակը խառնելու ձող", "անթրոց"),
		new question("չարչի", "փերեզակ"),
		new question("տարվա առաջին պտուղը", "նուբար"),
		new question("շորի թև", "թեզանիք"),
		new question("հեծյալ զինվոր", "դրագուն"),
		new question("հարցական նշան", "պարույկ"),
		new question("ժամանակավոր փայտե կացարան", "բարաք"),
		new question("ուղտի սանձ", "պարուսաս"),
		new question("մայրաքղաքի բնակիչ", "ոստանիկ"),
		new question("նետերի աման", "կապարճ"),
		new question("հիվանդների կամ վիրավորների տեղափոխելու հարմարանք", "պատգարակ"),
		new question("քար նետող պարիսպը քանդելու պատերազմական հարմարանք", "բաբան"),
		new question("վայրի ճանճ", "գոռեխ"),
		new question("մոմի կամ լամպի վառվող թել", "պատրույգ"),
		new question("ժողովրդական երգերի թեմաներով գրված ստեղծագործություն", "ռապսոդիա"),
		new question("մտրակել", "ձաղկել"),
		new question("առաջնորդ", "ռահվիրա"),
		new question("կտուր", "ձեղուն"),
		new question("նախասրահ", "գավիթ"),
		new question("թևատակ", "անութ"),
		new question("նեցուկ", "սատար"),
		new question("լաբիրինթոս", "բավիղ"),
		new question("դշխուհի", "բամբիշ"),
		new question("թոթով", "թլվատ"),
		new question("շատ մութ", "ականակիր"),
		new question("ծարավ", "պապակ"),
		new question("իղձ", "փափագ"),
		new question("հողը վարելու գործիք", "արոր"),
		new question("որսի շուն", "քերծե"),
		new question("մառախուղ", "շամանդաղ"),
		new question("կշտամբել", "պախաարակել"),
		new question("գովերգել", "դրվատել"),
		new question("զեփյուռ", "խորշակ"),
		new question("անապական", "անբասիր"),
		new question("ծաղկաշղթա", "դրասանգ"),
		new question("գավաթ", "կթղա"),
		new question("տաղանդ", "քանքար"),
		new question("խոր հարգանք", "ակնածանք"),
		new question("վախենալ", "զարզանդել"),
		new question("հովիվ", "խաշնարած"),
		new question("մխիթարել", "ամոքել"),
		new question("սխալ", "թյուր"),
		new question("գույն", "թույր"),
		new question("խոնավ", "տամուկ"),
		new question("վտարանդի", "նժդեհ"),
		new question("օջախ", "ակութ"),
		new question("հնազանդվել", "անսալ"),
		new question("նահատակ", "մարտիրոս"),
		new question("բռունցք", "կռուփ"),
		new question("նահանջել", "ընկրկել"),
		new question("սին", "ընդունայն"),
		new question("հարևան", "դրացի"),
		new question("խորխորատ", "վիրապ"),
		new question("թովել", "առինքնել"),
		new question("մտածել", "խոկալ"),
		new question("սեթևեթել", "պչրել"),
		new question("անամոթ", "անպատկառ"),
		new question("նկարիչ", "նաղաշ"),
		new question("էգ ոչխար", "մաքի"),
		new question("զեբր", "ճանճկեն"),
		new question("կառքին լծված ձի", "վարգաձի"),
		new question("արու հավ", "որձակ"),
		new question("վայրի էշ", "ցիռ"),
		new question("առյուծի ձագ", "կորյուն"),
		new question("խոզի ձագ", "գոճի"),
		new question("սերունդ չտվող կին", "ամուլ"),
		new question("սերունդ չտվող կենդանի", "ստերճ"),
		new question("վայրի ոչխար", "մուֆլոն"),
		new question("արու էշ", "իշայր"),
		new question("ձկների խումբ", "վտառ"),
		new question("օձերի խումբ", "վտառ"),
		new question("թեթև նախաճաշ", "ակրատ"),
		new question("վատ լուր հաղորդող", "գուժկան"),
		new question("լավ(բարի)  լուր", "ավետիս"),
		new question("ամուսինների զույգ /լծկան զույգ եզներ/", "ամոլ"),
		new question("երիտասարդ աղջիկ", "պարմանուհի"),
		new question("գետի մասերի բաժանվելու հատվածը", "դելտա"),
		new question("եղջերաձև լուսին", "մահիկ"),
		new question("թագավորանիստ քաղաք", "ոստան"),
		new question("լեռնագագաթների հավերժական ձյուն", "զամպ"),
		new question("խճապատ ճանապարհ", "խճուղի"),
		new question("կամարակապ  որմնախորշ", "խոյակ"),
		new question("հոգևոր երգ", "շարական"),
		new question("հորդ անձրև", "տեղատարափ"),
		new question("ձիու համաչափ վազք", "վարգ"),
		new question("ձկնորսական ցանց", "ուռկան"),
		new question("կրոնավորի գլխարկ", "վեղար"),
		new question("որդեգրված երեխա", "հոգեզավակ"),
		new question("վագրի մորթի", "վագրենի"),
		new question("փոքրիկ եկեղեցի", "մատուռ"),
		new question("գինի մատուցող", "մատռվակ"),
		new question("ոտքի տակը", "ներբան"),
		new question("սրունքի ոսկոր", "ոլոք"),
		new question("սրունքի մկանային մասը", "սրնքակալ"),
		new question("օրհնած հացի(անթթխմոր) կտոր", "նշխար"),
		new question("մսի ջուր", "արգանակ"),
		new question("հողի կոշտ կտոր", "գուղձ"),
		new question("ոչխարների ձմեռանոց", "փարախ"),
		new question("ձիու սանձ", "երասան"),
		new question("հեթանոսական տաճար", "մեհյան"),
		new question("վզի զարդ", "մանյակ"),
		new question("թևի զարդ", "ապարանջան"),
		new question("այգու բերք հավաքելը", "այգեկութ"),
		new question("գլուխը կտրելու տեղ", "կառափնարան"),
		new question("պատշգամբի հենաձող", "բազրիք"),
		new question("խունկ ծխելու աման", "բուրվառ"),
		new question("որսի մսից կերակուր", "ամիճ"),
		new question("ոչխարի հոտը պահող", "հոտաղ"),
		new question("թագավորի օրենքների ամբողջությունը", "հրովարտակ"),
		new question("թագավորի հրամաններն ազդարարող", "մունետիկ"),
		new question("ամառանոց եկած մարդ", "հովեկ"),
		new question("պալատական պաշտոնյա", "դրանիկ"),
		new question("թեթև   հանցանք", "զանցանք"),
		new question("տողադարձի գիծ", "ենթամնա"),
		new question("անդորր, հանգիստ վիճակ", "նիրվանա"),
		new question("լույսերը վառելու ժամանակը", "ճրագալույց"),
		new question("փոքր նավ", "մակույկ"),
		new question("շարած պատ", "որմածք"),
		new question("հավատացյալների  համայնական  ընթրիք", "ագապ"),
		new question("կարի թել", "դերձան"),
		new question("քաղաքամերձ բնակավայր/ քաղաքի ծայրամաս", "արվարձան"),
		new question("խնջույքներում պարող կին", "վարձակ"),
		new question("էմալով պատված", "արծնապատ"),
		new question("ոչխարի հոտի խմբվելը", "մակաղել"),
		new question("խակ պտուղ", "ազոխ"),
		new question("հովիվների  թաղիքե  անթև  վերարկու", "գաբանակ"),
		new question("մեղմ բնավորության տեր", "քաղցրաբարո"),
		new question("լսելու համար հաճելի", "ախորժալուր"),
		new question("բուրդ գզելու սանր", "սանդ"),
		new question("ծղոտե ծածկոց", "պանամա"),
		new question("սահմանագլխին ապրող նախարար", "բդեշխ"),
		new question("մահճակալի վերևի մաս", "սնար"),
		new question("թռչուններ որսալու ցանց", "վարմ"),
		new question("նավի առաջամաս", "ցռուկ"),
		new question("զինված թիկնապահների խումբ", "ասպախումբ"),
		new question("ջութակ նվագելու աղեղ", "կնտնտոց"),
		new question("թագավորական  թիկնոց", "ծիրանի"),
		new question("ցորենի հասկի փուշ", "քիստ"),
		new question("գլխարկի վրա պակցված նշան", "կոկարդ"),
		new question("վիրաբուժական սուր դանակ", "նշտար"),
		new question("գլխի փաթթոց", "ապարոշ"),
		new question("տղամարդու լայն ու երկար վերարկու", "կապա"),
		new question("առավոտյան վերկացի ազդանշան", "այգանվագ"),
		new question("ճահճոտ ու ավազոտ տեղ,որտեղով քայլելիս խրվում են", "խրուտ"),
		new question("եկեղեցական հատուկ զգեստ, կապա", "պարեգոտ"),
		new question("վուշի բարակ թել", "բեհեզ"),
		new question("մեծ գեղարդ", "մկունդ"),
		new question("բարակ ձայնով երգել", "մղմղալ"),
		new question("ընտիր կերակուր", "համադամ"),
		new question("երես ներկելու քսուք, շպար", "սնգույր"),
		new question("փամփուշտի խողովակաձև մասը", "պարկուճ"),
		new question("թրծած աղյուս", "կղմինդր"),
		new question("կտավատի թելից հյուսված գործվածք", "քաթան"),
		new question("ցամաքի մեջ փոքրիկ շերտերով հողամաս", "ծովախորշ"),
		new question("փողոցային կռիվների ժամանակ կառուցված պաշտպանական թումբ", "բարիկադ"),
		new question("խաղողի հյութը քամելու ավազան, գուռ", "հնձան"),
		new question("բարձր ճյուղեր ունեցող", "բարձրուղեշ"),
		new question("դուռը փակելու փայտե կամ երկաթե ձող", "սողնակ")
	};
	
	public static question[] getArray()
	{
		Integer[] numbers = new Integer [questions.length];
		question[] ret=new question[questions.length];
		
		int i;
		
		for(i=0;i<numbers.length;++i)
			numbers[i]=i;
		Collections.shuffle(Arrays.asList(numbers));
		
		for(i=0;i<numbers.length;++i)
			ret[i]=questions[numbers[i]];
		return ret;
	}
}
